sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
script:
  - echo "skipping tests"
before_deploy:
  - yarn run build --prod
  - cp ./CNAME ./dist/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
